// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpeBWQRl2kNVVpdQz1oQLQx9nu8d_2OC8',
    appId: '1:72874731969:web:e6c8d284c490956de4a740',
    messagingSenderId: '72874731969',
    projectId: 'survival-english-d8c02',
    authDomain: 'survival-english-d8c02.firebaseapp.com',
    storageBucket: 'survival-english-d8c02.firebasestorage.app',
    measurementId: 'G-VR4MDTXW6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7D-t31RwD2zb7xcYWPzF0YidHKR_-Fo',
    appId: '1:72874731969:android:97156d1b1e408765e4a740',
    messagingSenderId: '72874731969',
    projectId: 'survival-english-d8c02',
    storageBucket: 'survival-english-d8c02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchl7ZgvUU5X6fOEI9rnjiRMfvqlDbs6U',
    appId: '1:72874731969:ios:a43ec9c121a1ad23e4a740',
    messagingSenderId: '72874731969',
    projectId: 'survival-english-d8c02',
    storageBucket: 'survival-english-d8c02.firebasestorage.app',
    iosBundleId: 'com.example.survivalEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchl7ZgvUU5X6fOEI9rnjiRMfvqlDbs6U',
    appId: '1:72874731969:ios:a43ec9c121a1ad23e4a740',
    messagingSenderId: '72874731969',
    projectId: 'survival-english-d8c02',
    storageBucket: 'survival-english-d8c02.firebasestorage.app',
    iosBundleId: 'com.example.survivalEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpeBWQRl2kNVVpdQz1oQLQx9nu8d_2OC8',
    appId: '1:72874731969:web:732767afd1a0a048e4a740',
    messagingSenderId: '72874731969',
    projectId: 'survival-english-d8c02',
    authDomain: 'survival-english-d8c02.firebaseapp.com',
    storageBucket: 'survival-english-d8c02.firebasestorage.app',
    measurementId: 'G-0RFVSXHNL8',
  );
}
